# Generated by Django 6.0.6 on 2026-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reg_number_or_staff_id', models.CharField(max_length=50)),
                ('lab_room', models.CharField(choices=[('Lab 1', 'SIIS Main Lab 1'), ('Lab 2', 'SIIS PostGraduate Lab 2'), ('Lab 3', 'SIIS Network Lab 3')], max_length=20)),
                ('computer_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Hardware', 'Hardware Failure (Mouse, Keyboard, Screen)'), ('Software', 'Software/OS Issue (Crashing, Missing Apps)'), ('Network', 'Network/Internet Disconnection'), ('Staff Complain', 'Staff/Lab Assistance Complaint')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
