# Generated by Django 6.0.6 on 2026-07-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labticket',
            name='lab_room',
            field=models.CharField(choices=[('SIIS Lab', 'SIIS Lab'), ('Computer Lab 1', 'Computer Lab 1'), ('Multidisciplinary Lab', 'Multidisciplinary Lab')], max_length=30),
        ),
    ]
