# Generated by Django 6.0.6 on 2026-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0002_alter_labticket_lab_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='labticket',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='labticket',
            name='reg_number_or_staff_id',
        ),
        migrations.AddField(
            model_name='labticket',
            name='reported_by',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff/Faculty', 'Staff / Faculty Member'), ('Anonymous', 'Prefer not to say')], default='Anonymous', max_length=30),
        ),
    ]
