# Generated by Django 4.2.29 on 2026-07-15 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab_portal', '0003_remove_labticket_email_remove_labticket_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labticket',
            name='admin_feedback',
        ),
        migrations.RemoveField(
            model_name='labticket',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='labticket',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labticket',
            name='student_email',
            field=models.EmailField(blank=True, help_text='Optional for status email updates', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='labticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='computer_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='lab_room',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Assigned', 'Assigned to Technician'), ('Resolved', 'Resolved / Work Done')], default='Pending', max_length=20),
        ),
    ]
