# Generated by Django 4.2.29 on 2026-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0004_remove_labticket_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Fault (Monitor, Mouse, Keyboard, PC)'), ('SOFTWARE', 'Software Issue (OS Crash, Missing Apps, Activation)'), ('NETWORK', 'Network & Internet Connectivity Outage'), ('POWER', 'Power Supply & UPS Failure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='lab_room',
            field=models.CharField(choices=[('SIIS_LAB_1', 'SIIS Lab 1 (Ground Floor)'), ('SIIS_LAB_2', 'SIIS Lab 2 (First Floor)'), ('SIIS_POSTGRAD', 'SIIS PostGrad Lab'), ('MAIN_LIBRARY_LAB', 'Main Library Computer Lab')], max_length=50),
        ),
    ]
