# Generated by Django 4.2.29 on 2026-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0005_alter_labticket_category_alter_labticket_lab_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Fault (Keyboard, Mouse, Monitor, PC)'), ('SOFTWARE', 'Software & OS issues'), ('NETWORK', 'Network & Internet Connection issues'), ('POWER', 'Power & Electrical supply issues')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labticket',
            name='lab_room',
            field=models.CharField(choices=[('LAB_1', 'Lab 1'), ('SIIS_LAB', 'SIIS Lab'), ('MULTIDISCIPLINARY', 'Multidisciplinary Lab')], max_length=50),
        ),
    ]
