# Generated by Django 4.2.29 on 2026-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0006_alter_labticket_category_alter_labticket_lab_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='labticket',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Upload an error screenshot', null=True, upload_to='ticket_screenshots/'),
        ),
    ]
