# Generated by Django 4.2.29 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_portal', '0007_labticket_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Fault (Keyboard, Mouse, Monitor, PC)'), ('SOFTWARE', 'Software & OS issues'), ('NETWORK', 'Network & Internet Connection issues'), ('POWER', 'Power & Electrical supply issues'), ('STAFF_COMPLAINT', 'Staff Complaint')], max_length=100),
        ),
    ]
